# Generated by Django 2.0.1 on 2018-01-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUA', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenseKey',
        ),
    ]
