# Generated by Django 2.0.1 on 2018-01-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUA', '0005_auto_20180107_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='ts',
            field=models.CharField(default='1515412075', max_length=20),
        ),
    ]
