# Generated by Django 2.0.1 on 2018-01-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASA', '0006_auto_20180108_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenseKey',
        ),
    ]
