# Generated by Django 2.0.1 on 2018-01-27 00:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=100)),
                ('Data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='HCenterEmployee',
            fields=[
                ('EmployeeID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='HCenterSPOC',
            fields=[
                ('SPOCID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('passhash', models.CharField(max_length=100)),
                ('Data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('HealthCenterID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Data', django.contrib.postgres.fields.jsonb.JSONField(default={'asa_sign': False})),
            ],
        ),
        migrations.AddField(
            model_name='hcenterspoc',
            name='HealthCenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HCenter.HealthCenter'),
        ),
        migrations.AddField(
            model_name='hcenteremployee',
            name='HCenterSPOC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HCenter.HCenterSPOC'),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='SPOCID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HCenter.HCenterSPOC'),
        ),
    ]
