# Generated by Django 2.0.2 on 2018-03-03 19:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HCenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GIDMap',
            fields=[
                ('gi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cQueue', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecordMaps',
            fields=[
                ('HealthID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
