# Generated by Django 2.0.1 on 2018-01-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AADHARSPOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPOCID', models.CharField(max_length=100)),
                ('passhash', models.CharField(max_length=100)),
            ],
        ),
    ]
